
services:
  db:
    image: postgres:15
    restart: always
    container_name: taskmanager-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - ./storage/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.4-alpine3.21
    container_name: taskmanager-redis
    ports:
      - "6380:6379"

  migrations:
    build: .
    container_name: taskmanager-migrations
    command: bash -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}

  seeds:
    build: .
    container_name: taskmanager-seeds
    command: python app/db/seeder.py
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env


  web:
    build: .
    container_name: taskmanager-api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  celery_worker:
    build: .
    container_name: taskmanager-celery-worker
    command: celery -A app.core.celery.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  celery_beat:
    build: .
    container_name: taskmanager-celery-beat
    command: celery -A app.core.celery.celery_worker.celery_app beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
