"""autogenerate

Revision ID: e5a7e9403fb7
Revises: 852bd9b83d49
Create Date: 2025-06-18 17:32:36.512236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a7e9403fb7'
down_revision: Union[str, Sequence[str], None] = '852bd9b83d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_overdue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_overdue')
    # ### end Alembic commands ###
